use_frameworks!

target 'InAppMessaging_Example' do
  pod 'InAppMessaging', :path => '../'

  target 'InAppMessaging_Tests' do
    inherit! :search_paths
    pod 'InAppMessaging', :path => '../'
    pod 'Quick'
    pod 'Nimble'
  end
end

