use_frameworks!

target 'RakutenInsights_Example' do
  pod 'RakutenInsights', :path => '../'

  target 'RakutenInsights_Tests' do
    inherit! :search_paths
  pod 'RakutenInsights', :path => '../'
    
  end
end
